WebNursePlanning/Models/AppointmentViewModel.cs
using DomainModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebNursePlanning.Models
{
    public class AppointmentViewModel
    {
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        [DataType(DataType.Time)]
        public DateTime Time { get; set; }
        [Display(Name = "A domicile")]
        public bool AtHome { get; set; }
        [Display(Name = "Infirmier(e)")]
        public string NurseId { get; set; }
        [Display(Name = "Patient(e)")]
        public string PatientId { get; set; }
        public string Description { get; set; }
        [Display(Name = "Status")]
        public Guid StatusId { get; set; }
        public ICollection<Message> Messages { get; set; }
    }
}

WebNursePlanning/Controllers/AppointmentsController.cs
using DomainModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Repository.Interfaces;
using Microsoft.AspNetCore.Identity;
using WebNursePlanning.Models;
using System.Threading.Tasks;
using System;
using System.Linq;

namespace WebNursePlanning.Controllers
{
    public class AppointmentsController : Controller
    {
        private readonly IAppointmentRepository _appointmentRepository;
        private readonly INurseRepository _nurseRepository;
        private readonly IPatientRepository _patientRepository;
        private readonly IStatusRepository _statusRepository;
        private readonly UserManager<Person> _userManager;
        private readonly SignInManager<Person> _signInManager;

        public AppointmentsController(IAppointmentRepository appointmentRepository, INurseRepository nurseRepository, IPatientRepository patientRepository, IStatusRepository statusRepository, UserManager<Person> userManager, SignInManager<Person> signInManager)
        {
            _appointmentRepository = appointmentRepository;
            _nurseRepository = nurseRepository;
            _patientRepository = patientRepository;
            _statusRepository = statusRepository;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        // GET: Appointments
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            var listAppointments = await _appointmentRepository.ListAppointmentsById(user.Id);
            return View(listAppointments);
        }


        // GET: Appointments/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _appointmentRepository.Details(id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // GET: Appointments/Create
        public async Task<IActionResult> Create()
        {
            //recherche de tous les infirmiers , les patients pour creer un rdv "en cours de validation"
            //var listNurses = ;
            var listNurses = await _nurseRepository.ListNurses();
            var dicoNurses = listNurses.ToDictionary(b => b.Id, b => b.LastName + " " + b.FirstName);
            ViewData["NurseId"] = new SelectList(dicoNurses, "Key", "Value");

            var listPatients = await _patientRepository.ListPatients();
            var dicoPatients = listPatients.ToDictionary(b => b.Id, b => b.LastName + " " + b.FirstName);
            ViewData["PatientId"] = new SelectList(dicoPatients, "Key", "Value");

            ViewData["StatusId"] = await _statusRepository.GetStatusId("En attente");
            
            return View();
        }

        // POST: Appointments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                //appointment.Id = Guid.NewGuid();
                await _appointmentRepository.Create(appointment);

                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index");
        }

        // GET: Appointments/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _appointmentRepository.Details(id);
            if (appointment == null)
            {
                return NotFound();
            }

            var listNurses = await _nurseRepository.ListNurses();
            var dicoNurses = listNurses.ToDictionary(b => b.Id, b => b.LastName + " " + b.FirstName);
            ViewData["NurseId"] = new SelectList(dicoNurses, "Key", "Value", appointment.NurseId);

            var listPatients = await _patientRepository.ListPatients();
            var dicoPatients = listPatients.ToDictionary(b => b.Id, b => b.LastName + " " + b.FirstName);
            ViewData["PatientId"] = new SelectList(dicoPatients, "Key", "Value", appointment.PatientId);
            ViewData["StatusId"] = new SelectList(await _statusRepository.ListStatuses(), "Id", "Name", appointment.StatusId);
           
            return View(appointment);
        }

        // POST: Appointments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Date,Description,AtHome,NurseId,PatientId,StatusId")] Appointment appointment)
        {
            if (id != appointment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _appointmentRepository.Edit(appointment);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppointmentExists(appointment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            var listNurses = await _nurseRepository.ListNurses();
            var dicoNurses = listNurses.ToDictionary(b => b.Id, b => b.LastName + " " + b.FirstName);
            ViewData["NurseId"] = new SelectList(dicoNurses, "Key", "Value", appointment.NurseId);

            var listPatients = await _patientRepository.ListPatients();
            var dicoPatients = listPatients.ToDictionary(b => b.Id, b => b.LastName + " " + b.FirstName);
            ViewData["PatientId"] = new SelectList(dicoPatients, "Key", "Value", appointment.PatientId);
            ViewData["StatusId"] = new SelectList(await _statusRepository.ListStatuses(), "Id", "Name", appointment.StatusId);

            return View(appointment);
        }

        // GET: Appointments/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _appointmentRepository.Details(id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // POST: Appointments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _appointmentRepository.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private bool AppointmentExists(Guid id)
        {
            return _appointmentRepository.Exists(id);
        }
    }
}

WebNursePlanning/Views/Appointments/Components/CreateAppointmentCalendarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repository.Interfaces;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace WebNursePlanning.Shared.Components
{
    public class CreateAppointmentCalendarViewComponent : ViewComponent
    {
        private readonly IAppointmentRepository _appointmentRepository;
        public CreateAppointmentCalendarViewComponent(IAppointmentRepository appointmentRepository)
        {
            _appointmentRepository = appointmentRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(string id)
        {

            Dictionary<string, List<TimeSpan>> dico = await _appointmentRepository.GetListAvailableAppointments(id);

            ViewData["AppointmentsAvailables"] = dico;
            return View();
        }
       
    }
}

WebNursePlanning/Views/Appointments/Components/EditAppointmentCalendarViewComponent.cs
using DomainModel;
using Microsoft.AspNetCore.Mvc;
using Repository.Interfaces;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace WebNursePlanning.Shared.Components
{
    public class EditAppointmentCalendarViewComponent : ViewComponent
    {
        private readonly IAppointmentRepository _appointmentRepository;
        public EditAppointmentCalendarViewComponent(IAppointmentRepository appointmentRepository)
        {
            _appointmentRepository = appointmentRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(string personId, List<Appointment> appToEdit)
        {

            Dictionary<string, List<TimeSpan>> dico = await _appointmentRepository.GetListAvailableAppointments(personId, appToEdit);

            ViewData["AppointmentsAvailables"] = dico;
            return View();
        }
       
    }
}

WebNursePlanning/Views/Appointments/Create.cshtml
@model DomainModel.Appointment
@using Microsoft.AspNetCore.Identity
@inject SignInManager<DomainModel.Person> SignInManager
@inject UserManager<DomainModel.Person> UserManager

@{
    ViewData["Title"] = "Create";

}

<h1>Prise de Rendez-Vous</h1>

<h4>Veuillez selectionner un horaire parmi les propositions</h4>

<div class="row">
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            @await Component.InvokeAsync("CreateAppointmentCalendar", UserManager.GetUserId(User))
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="AtHome" />@Html.DisplayNameFor(model => model.AtHome)
                </label>
            </div>
            @if (User.IsInRole("ROLE_ADMIN"))
            {//Si l'utilisateur connecté est infirmier(role admin)
                <div class="form-group">
                    <input asp-for="NurseId" style="display:none;" value="@UserManager.GetUserId(User)" />
                </div>
                <div class="form-group">
                    <label asp-for="PatientId" class="control-label"></label>
                    <select asp-for="PatientId" class="form-control" asp-items="ViewBag.PatientId"></select>
                </div>
            }
            else if (User.IsInRole("ROLE_USER"))
            {//Si l'utilisateur est un patient (role user)
                <div class="form-group">
                    <label asp-for="NurseId" class="control-label"></label>
                    <select asp-for="NurseId" class="form-control" asp-items="ViewBag.NurseId"></select>
                </div>
                <div class="form-group">
                    <input asp-for="PatientId" style="display:none;" value="@UserManager.GetUserId(User)" />
                </div>
            }

            <div class="form-group">
                <input asp-for="StatusId" style="display:none;" value="@ViewBag.StatusId" />
            </div>
            <div class="form-group">
                <input type="submit" value="Créer" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebNursePlanning/Views/Appointments/Delete.cshtml
@model DomainModel.Appointment

@{
    ViewData["Title"] = "Delete";
}

<h1>Suppression de RDV</h1>

<h3>Etes vous sur de vouloir annuler ceci?</h3>
<div>
    <hr />
    <h4>Rendez-vous</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AtHome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AtHome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NurseId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nurse.LastName)
            @Html.DisplayFor(model => model.Nurse.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PatientId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.LastName)
            @Html.DisplayFor(model => model.Patient.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Supprimer" class="btn btn-danger" /> |
        <a asp-action="Index">Retour à la liste</a>
    </form>
</div>

WebNursePlanning/Views/Appointments/Details.cshtml
@model DomainModel.Appointment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Rendez-Vous</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AtHome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AtHome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model=>model.NurseId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nurse.LastName)
            @Html.DisplayFor(model => model.Nurse.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PatientId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.LastName)
            @Html.DisplayFor(model => model.Patient.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editer</a> |
    <a asp-action="Index">Retour à la liste</a>
</div>

WebNursePlanning/Views/Appointments/Edit.cshtml
@model DomainModel.Appointment
@using Microsoft.AspNetCore.Identity
@inject SignInManager<DomainModel.Person> SignInManager
@inject UserManager<DomainModel.Person> UserManager

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Rendez-Vous</h4>
<hr />
<div class="row">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            @await Component.InvokeAsync("EditAppointmentCalendar", new { personId = UserManager.GetUserId(User), appToEdit = new List<DomainModel.Appointment> { Model } })
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="AtHome" /> @Html.DisplayNameFor(model => model.AtHome)
                </label>
            </div>
            @if (User.IsInRole("ROLE_ADMIN"))
            {//Si le l'utilisateur connecté est infirmier(role admin)
                <div class="form-group">
                    <input asp-for="NurseId" class="form-control" style="display:none;" value="@UserManager.GetUserId(User)" />
                </div>
                <div class="form-group">
                    <label asp-for="PatientId" class="control-label"></label>
                    <select asp-for="PatientId" class="form-control" asp-items="ViewBag.PatientId"></select>
                </div>
            }
            else if (User.IsInRole("ROLE_USER"))
            {//Si l'utilisateur est un patient (role user)
                <div class="form-group">
                    <label asp-for="NurseId" class="control-label"></label>
                    <select asp-for="NurseId" class="form-control" asp-items="ViewBag.NurseId"></select>
                </div>
                <div class="form-group">
                    <input asp-for="PatientId" class="form-control" style="display:none;" value="@UserManager.GetUserId(User)" />
                </div>
            }
            <div class="form-group">
                <label asp-for="StatusId" class="control-label"></label>
                <select asp-for="StatusId" class="form-control" asp-items="ViewBag.StatusId"></select>
                <span asp-validation-for="StatusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Modifier Rdv" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}